version: '3.8'

services:
  db:
    build: .
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    entrypoint: >
      /bin/sh -c "
        echo 'db:5432:mydb:myuser:mypassword' > /tmp/pgpassfile &&
        chmod 600 /tmp/pgpassfile &&
        /entrypoint.sh
      "

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: stockscreener_api
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      API_PORT: "8000"
      ALPACA_API_KEY: "${ALPACA_API_KEY}"
      ALPACA_API_SECRET: "${ALPACA_API_SECRET}"
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build:
      context: ../angular-client
      dockerfile: Dockerfile
    container_name: stockscreener_client
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  postgres_data:
  pgadmin_data: